### ISSUE TITLE
IllegalStateException: Can not perform this action after onSaveInstanceState 

### ISSUE THREAD

**Issue by omidjoon** [vanniktech/RxPermission#60] opened 2018-12-26 13:14 UTC
i want to check the permission before going to the map fragment, when i grant the permission the fragment doesnt start and this error logged. when i try for second time it works. 

what happened?

**Comment by omidjoon** [comment] 2018-12-29 06:17
i uploaded my code, in addition i used https://github.com/ncapdevi/FragNav to manage fragments. i hope it is helpful

[code.zip](https://github.com/vanniktech/RxPermission/files/2716096/code.zip)

**Comment by vanniktech** [comment] 2018-12-29 09:01
I'm sorry but I won't be looking and debugging your code. This library is offered as is and I'm maintaining it in my free time. Feel free to dig in and analyze the underlying issue of your problem. 
If you don't have an executable test case or some steps to reproduce in the sample app, I'll close this

**Comment by vanniktech** [comment] 2019-01-03 15:35
I'm closing this issue due to inactivity. If you have any further input on the issue, don't hesitate to reopen this issue or post a new one.

**Closed by vanniktech** 2019-01-03 15:35 UTC
Labels: needs info
